version: "3.9"
services:
  db:
    image: mariadb:11.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-card_memory_db}
      MYSQL_USER: ${DB_USER:-appuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 20s
      retries: 10

  app:
    build: .
    image: ${APP_IMAGE:-}
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=${DB_NAME:-card_memory_db}
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    ports:
      - "${APP_PORT:-8081}:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mariadb_data:
