version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  javafx-app:
    build: .
    container_name: javafx-app-container
    depends_on:
      mariadb:
        condition: service_healthy

    ports:
      - "5900:5900"
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge